---

    - name: configure etcd details
      replace:
          dest=/etc/tendrl/alerting/alerting.conf.yaml
          regexp='0.0.0.0'
          replace="{{ lookup('ini', 'ip section=etcd-server file=tendrl.conf') }}"
