---

    - name: configure node-monitoring
      replace:
          dest=/etc/tendrl/node-monitoring/node-monitoring.conf.yaml
          regexp='0.0.0.0'
          replace="{{ lookup('ini', 'ip section=etcd-server file=tendrl.conf') }}"

